### ISSUE TITLE
Помилка авторизації

### ISSUE THREAD

**Issue by yanaizmene** [vitalikdanchenko/turbosms#4]
Превіт. 

З 60 спроб відправити смс, 10 невдалих з повідомленням "Вы не авторизированы".

Ніяких закономірностей не виявлено. Просто рандомні повідомлення не авторизовуються.

rails 4.2.5
turbosms (0.1.4)

Є якісь думки? Проблема в джемі чи в самому турбосмс?

**Comment by vitalikdanchenko** [comment]
Привіт, я провів стрес тест на 20 повідомлень і усі були доставлені з першого разу -https://gist.github.com/vitalikdanchenko/f51f5fed2d392964e6b49965c39571ac

Як саме джем використовується у проекті? Яка ймовірність того, що залишився працювати  інстанс із старим паролем до шлюзу?

**Comment by yanaizmene** [comment]
Пароль в мене тільки один був. Він не змінювався увесь час що я використовую джем.

Звичаний рельсовий застосунок. В ApplicationController маю метод send_sms
https://gist.github.com/yanaizmene/2f5e77ff0e8b0b7d7efb4de40e2f66c1

require "#{Rails.root}/lib/gem_ext/turbosms/api.rb" це я в якості проби перевантажив ваш метод send_sms

Прибрав перевірку на authorized?.
https://github.com/vitalikdanchenko/turbosms/blob/master/lib/turbosms/api.rb#L15

Спостерігаю, сьогодні помилок не було.

**Comment by yanaizmene** [comment]
Забув сказати, 60 спроб відправити смс то не підряд було, а на протязі місяця.

**Comment by vitalikdanchenko** [comment]
Коли викликається метод `authorize`? Більш за все, що протягом тижня закінчився термін дії куки, яка використовується для авторизації. Також я б не рекомендував відправляти повідомлення безпосередньо з контролера під час запиту. Краще це робити в фоні.

**Comment by yanaizmene** [comment]
В мене тепер кожний виклик send_sms смикає authorize примусово.

В тому проекті бекграунд джоби — оверінжінірінг.

**Comment by molfar** [comment]
Така ж сама проблема спостерігається з rails. Дуже часто випадає "Вы не авторизированы"

**Comment by molfar** [comment]
кукіс зберігається як інстанс змінна... при перезапуску додатка все ж буде обнулятись. зазвичий сервисі повинен видавати постійний токен, який один раз прописуєтьс в конфіг

**Comment by vitalikdanchenko** [comment]
@molfar нажаль `turbosms` вимагає попередньої авторизації і працює лише з використанням кук. Можете, будь ласка, описати у якиї випадках відповідь від `turbosms` - "Вы не авторизированы"?

**Comment by yanaizmene** [comment]
Можете перевантажити метод send_sms. Я пів року живу на цьому рішенні. Жодної помилки при відправці смс не було.
https://gist.github.com/yanaizmene/d721a7d8393d9c6a6c74f06063ab48dd

**Comment by vitalikdanchenko** [comment]
у даній реалізацію на кожну відправку повідомілення буде виконуватися два мережевих запити, що не є припустимо, якщо робити розсилку часто і у великій кількості

**Comment by molfar** [comment]
потрібно видавати постійний токен, як це робиться у всіх подібних сервісах. цей кукіс по суті і є токен, просто потрібно його сприймати як довготривалим та видавати а інтерфейсі вашого сервісу

**Comment by vitalikdanchenko** [comment]
@molfar `turbosms` це сторонній сервіс і я такий самий його користувач його як і Ви, тому не маю змоги впливати на API, який надає `turbosms`.

**Comment by molfar** [comment]
@vitalikdanchenko а, все зрозумів. я чомусь подумав що це офіційний гем турбосмс) 
вам велика подяка за те що зробили хоч такий функціонал. 
а то ще в їх сервісі так все непродумано - то це вже питання не до вас тоді)
